### ISSUE TITLE
Support variable in keyword name for statistics

### ISSUE THREAD

**Issue by leeuwe** [pbylicki/rfhub2#291]
Currently, it looks to me as if keywords using the Embedded arguments approach are not counted in the Statistics. For me, that's a dealbreaker. I have little knowlede about how this should work, but I think it can work if the report.xml file is create with TRACE logging.
This would give the following:
<kw name="I click on activity &quot;xyz&quot;" library="GebiedsInfo">
<msg timestamp="20201022 13:05:45.004" level="TRACE">Arguments: [ ${activity}='xyz' ]</msg>

With this one should be able to reverse engineer what the keyword with embedded argument was.

**Comment by MaciejWiczk** [comment]
Hi @leeuwe, You are right that embedded keywords are not taken into account when calculating statistics. The root of this issue lies between RfHub and Robotframework itself. When parsing execution results, to collect statistics, RfHub ges through output.xml file, that looks like below:
```
<kw name="Open ${single_class_lib} In Left Panel">
<kw name="Run Keyword And Return Status" library="BuiltIn">
<doc>Runs the given keyword with given arguments and returns the status as a Boolean value.</doc>
<arguments>
<arg>Element Should Not Be Visible</arg>
<arg>${hamburger}</arg>
```
At first line You have embedded keyword, however it names differ from its definition `Open ${library} In Left Panel`, because of different variable used in test. If string value is used instead of variable, it works the same. Matching definition with execution is a tricky one to do. I was thinking of rising issue on RFWK side, so thath original keyword definition would be saved in output.xml, so that root cause would be fixed. 

Currently for joining those data on RfHub side we use SQL joins. I think this could be updated for embedded keywords, to remove variables from them, but that would be half-good solution, because of injecting literall instead of variable in keyword execution. I;m going to investigate regexp_join but that's wrong from perfomance point of view.

**Comment by leeuwe** [comment]
Thanks for your expanation. This is why I suggested this should be possible when one logs with TRACE, as this would make it doable in my opinion:

```
<test id="s1-s1-s1-t1" name="Test Embedded Logging">
<kw name="Userkeyword with ${Override}">
<msg timestamp="20201026 10:55:10.354" level="TRACE">Arguments: [ ${EmbeddedArgument}='https://www.google.com' ]</msg>
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>${EmbeddedArgument}</arg>
<arg>gc</arg>
</arguments>
```

Attached whole logging and RF example file to run, with TRACE enabled, so you can run and see what I mean.
[EmbeddedArgs.zip](https://github.com/pbylicki/rfhub2/files/5438103/EmbeddedArgs.zip)

Hope this helps!

**Comment by MaciejWiczk** [comment]
Ok, I will check that on Robotframework API side which we use for parsing output.xml

**Comment by MaciejWiczk** [comment]
@leeuwe I took a longer look on that issue. Sadly, arguments are only passed on trace level :( 
I also took a look into Robotframework itself, and tested how keywords are processed, and found a place where embedded kewords are "translated" from `Add 1 To 2` to `Add ${n} to ${m}`. If I manage, I will raise and issue and PR in robotframework. I will keep this issue updated.

**Comment by leeuwe** [comment]
@MaciejWiczk Greatly appreciated! Thanks for your effort.

**Comment by MaciejWiczk** [comment]
This one is finally done. Sorry for the long wait @leeuwe

**Comment by leeuwe** [comment]
Cool! It's open source, I'm already happy you figured it out. Much appreciated 👍
