### ISSUE TITLE
Missing requirements in setup.py

### ISSUE THREAD

**Issue by Snooz82** [pbylicki/rfhub2#54]
With pip install there are missing modules:

```python
install_requires=[
        'Click>=7.0',
        'fastapi>=0.30.0',
        'robotframework>=3.0.0',
        'SQLAlchemy>=1.1.0',
        'requests>=2.10.0'
],
```

it is missing `uvicorn` and `aiofiles`

kind regards

**Comment by MaciejWiczk** [comment]
Hi @Snooz82 I'm a bit surprised by that, since `uvicorn` and `aiofiles` are dependencies of [fastapi](https://github.com/tiangolo/fastapi/blob/master/pyproject.toml#L62)
. Could You tell me on what version of python and OS did You install rfhub2?

I just did uninstall and install rfhub2 from PyPI, and on windows/linux it was missing uvicorn and aiofiles. Thanks for spotting that!

**Comment by MaciejWiczk** [comment]
Fixed in #6

**Comment by Snooz82** [comment]
It was on windows 10 with python 3.7.4

**Comment by MaciejWiczk** [comment]
PyPI is updated. Should be alright :)
